CREATE TABLE teaclippings (
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
name text not null,
tea_type text not null,
caffeine text not null,
taste text not null,
details text,
temp integer,
brew_time text
);
